language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- curl -L https://github.com/pololu/lsm6-arduino/archive/master.tar.gz | tar xz -C /tmp

env:
- BOARD=leonardo

script:
- for e in examples/*; do
    platformio ci --board=$BOARD --lib=. --lib="/tmp/lsm6-arduino-master/" $e/*;
  done
